num=-5
print("el tipo es ")
print(type(num))
print("el valor absoluto es ")
print (abs(num))
print( "la division es ")
var=7/2
print (var)
print("el cociente es ")
var1=7//2
print(var1)
print("el resto es ")
var2=7%2
print(var2)
print("la potencia")
var3= 3**2
print(var3)
print("la pontencia")
var4 = pow(3, 2)
print(var4)
print("conviento a int ")
var5=int(7.2)
print(type(var5))
print(var5)
print("convierto a real ")
var6=float(234)
print(type(var6))
print(var6)
print("division")
var7 =divmod(7, 2)
print(var7)
print("raiz cuadrada")
import math
var8=math.sqrt(9)
print(var8)